listen_addresses = '*'

shared_buffers = 1GB
work_mem = 32MB

synchronous_commit = off
wal_buffers = 16MB # ХЗ сколько надо

max_connections = 100

effective_cache_size = 6GB
random_page_cost = 1.1

log_min_duration_statement = 500ms
#og_line_prefix = '%t [%p] %u@%d '
log_checkpoints = on
log_lock_waits = on