services:
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - DATABASE_URL=${DB_URL}
      - DATABASE_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    container_name: db
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    networks: 
      - app_network
  
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    container_name: redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks: 
      - app_network
  
  #redis-commander:
  #  image: rediscommander/redis-commander:latest
  #  ports:
  #    - "8081:8081"
  #  container_name: redis-com
  #  restart: unless-stopped
  #  networks:
  #    - app_network
  #  environment:
  #    - REDIS_HOSTS=local:redis:6379

  web:
    container_name: web
    build:
      context: .
    ports:
      - "8000:8000"
    networks: 
      - app_network
    volumes:
      #- ./project:/app
      - type: bind
        source: app
        target: /src/app
    depends_on:
      - db
      - redis
    restart: unless-stopped

  proxy:
    container_name: proxy
    image: nginx:alpine
    ports:
      "80:80"
    depends_on:
      - web
    restart: unless-stopped
    

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
  redis_data:
    driver: local
