services:
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    container_name: db
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network
  
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    container_name: redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - app_network
  
  redis-commander:
    image: rediscommander/redis-commander:latest
    ports:
      - "8081:8081"
    container_name: redis-com
    restart: unless-stopped
    environment:
      - REDIS_HOSTS=local:redis:6379
    networks:
      - app_network

  celery_worker:
    build:
      context: .
    container_name: worker
    volumes:
      - type: bind
        source: app
        target: /src/app

      - type: bind
        source: media
        target: /src/media
    restart: always
    env_file:
      - .env
    depends_on:
      - redis
    command: celery -A app.task_queue.celery_app worker --loglevel=info --logfile=app/worker.log
    networks:
      - app_network

  celery_beat:
    build:
      context: .
    container_name: beat
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - type: bind
        source: app
        target: /src/app
    depends_on:
      - redis
    command: celery -A app.task_queue.celery_app beat --loglevel=info
    networks:
      - app_network

  celery_flower:
    image: mher/flower:2.0
    container_name: flower
    restart: unless-stopped
    ports:
      - "5555:5555"
    env_file:
      - .env
    depends_on:
      - redis
      - celery_worker
    command: celery flower ${REDIS_URL} --port=5555
    networks:
      - app_network

  web:
    container_name: web
    build:
      context: .
    expose:
      - "8000"
    volumes:
      - type: bind
        source: app
        target: /src/app
    depends_on:
      - db
      - redis
      - minio
    restart: unless-stopped
    env_file:
      - .env
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000 --proxy-headers --forwarded-allow-ips=*
    networks:
      - app_network

  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    restart: unless-stopped
    networks:
      - app_network

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server --console-address ":9001" /data
    restart: unless-stopped
    networks:
      - app_network

  minio_client:
    image: minio/mc:latest
    container_name: minio_client
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until mc alias set local http://minio:9000 $${MINIO_ROOT_USER} $${MINIO_ROOT_PASSWORD}; do sleep 1; done;
      mc mb --ignore-existing user-avatars;
      mc mb --ignore-existing app-icons;
      mc mb --ignore-existing app-covers;
      mc mb --ignore-existing app-archives;
      mc anonymous set download avatars;
      mc anonymous set download app-icons;
      mc anonymous set download app-covers;
      exit 0;
      "
    networks:
      - app_network


networks:
  app_network:
    driver: bridge

volumes:
  db_data:
  redis_data:
  minio_data:
