"""Rename tables and add messages, discussions tables

Revision ID: 026e0df29ae3
Revises: 1a55c8d36887
Create Date: 2026-07-03 16:24:22.671256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '026e0df29ae3'
down_revision: Union[str, Sequence[str], None] = '1a55c8d36887'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.drop_constraint('review_app_id_fkey', 'review', type_='foreignkey')
    op.drop_constraint('purchase_app_id_fkey', 'purchase', type_='foreignkey')
    op.drop_constraint('cart_user_id_fkey', 'cart', type_='foreignkey')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('roles', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('balance', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('apps',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=400), nullable=True),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('public', sa.Boolean(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('genre', postgresql.ENUM('ADVENTURE', 'ACTION', 'PUZZLE', 'RACING', 'SANDBOX', 'MISC', name='gamegenre', create_type=False), nullable=True),
    sa.Column('category', postgresql.ENUM('APPLICATION', 'GAME', name='appcategory', create_type=False), nullable=False),
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.Column('keywords', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('publisher_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['publisher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('cart_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('cart_id', sa.Uuid(), nullable=False),
    sa.Column('app_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discussions',
    sa.Column('topic', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creator_id', sa.Uuid(), nullable=False),
    sa.Column('app_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('purchased_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('app_id', sa.Uuid(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id', 'user_id', 'app_id')
    )
    op.create_table('reviews',
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(length=400), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('app_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('discussion_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['discussion_id'], ['discussions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('cartitem')
    op.drop_table('app')
    op.drop_table('purchase')
    op.drop_table('review')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_table('cart')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('cart_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('cart_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('cart_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('user',
    sa.Column('username', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('roles', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False),
    sa.Column('balance', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('registered_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey')),
    sa.UniqueConstraint('email', name=op.f('user_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('review',
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('content', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('author_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('app_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['app.id'], name=op.f('review_app_id_fkey')),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name=op.f('review_author_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('review_pkey'))
    )
    op.create_table('purchase',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('purchased_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('app_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['app.id'], name=op.f('purchase_app_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('purchase_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('purchase_pkey'))
    )
    op.create_table('app',
    sa.Column('title', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('category', postgresql.ENUM('APPLICATION', 'GAME', name='appcategory', create_type=False), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('public', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('genre', postgresql.ENUM('ADVENTURE', 'ACTION', 'PUZZLE', 'RACING', 'SANDBOX', 'MISC', name='gamegenre', create_type=False), autoincrement=False, nullable=True),
    sa.Column('file_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('keywords', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False),
    sa.Column('publisher_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['publisher_id'], ['user.id'], name=op.f('app_publisher_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('app_pkey'))
    )
    op.create_table('cartitem',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('added_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('cart_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('app_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['app.id'], name=op.f('cartitem_app_id_fkey')),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], name=op.f('cartitem_cart_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('cartitem_pkey'))
    )
    op.drop_table('messages')
    op.drop_table('reviews')
    op.drop_table('purchases')
    op.drop_table('discussions')
    op.drop_table('cart_items')
    op.drop_table('carts')
    op.drop_table('apps')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
