"""empty message

Revision ID: 1a55c8d36887
Revises: 6d330e6a6553
Create Date: 2026-06-26 14:33:16.818206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '1a55c8d36887'
down_revision: Union[str, Sequence[str], None] = '6d330e6a6553'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='gamegenre',
        new_values=['ADVENTURE', 'ACTION', 'PUZZLE', 'RACING', 'SANDBOX', 'MISC'],
        affected_columns=[TableReference(table_schema='public', table_name='app', column_name='genre')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='gamegenre',
        new_values=['ADVENTURE', 'PUZZLE', 'RACING', 'SANDBOX'],
        affected_columns=[TableReference(table_schema='public', table_name='app', column_name='genre')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
