"""empty message

Revision ID: 4535f94e6a1a
Revises: c5b26b54a85d
Create Date: 2026-07-13 13:57:28.861437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4535f94e6a1a'
down_revision: Union[str, Sequence[str], None] = 'c5b26b54a85d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfers', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'transfers', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transfers', type_='foreignkey')
    op.drop_column('transfers', 'user_id')
    # ### end Alembic commands ###
