"""Add paths to files of app and user

Revision ID: 4f43b3e694f2
Revises: d67fc8f6867a
Create Date: 2026-07-17 14:27:40.763925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f43b3e694f2'
down_revision: Union[str, Sequence[str], None] = 'd67fc8f6867a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apps', sa.Column('archive_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('apps', sa.Column('thumbnail_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('apps', sa.Column('app_cover_paths', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('users', sa.Column('profile_picture_path', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apps', 'app_cover_paths')
    op.drop_column('apps', 'thumbnail_path')
    op.drop_column('apps', 'archive_path')
    op.drop_column('users', 'profile_picture_path')
    # ### end Alembic commands ###
