"""Made GIN partial

Revision ID: 6b47735111db
Revises: 7fd027ff31e2
Create Date: 2026-08-07 15:42:54.924962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b47735111db'
down_revision: Union[str, Sequence[str], None] = '7fd027ff31e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_apps_keywords_gin', 'apps', ['keywords'], unique=False, postgresql_using='gin', postgresql_where='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_apps_keywords_gin', table_name='apps', postgresql_using='gin', postgresql_where='public')
    # ### end Alembic commands ###
