"""empty message

Revision ID: 6d330e6a6553
Revises: a85cf81c92e3
Create Date: 2026-06-25 20:16:23.187412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d330e6a6553'
down_revision: Union[str, Sequence[str], None] = 'a85cf81c92e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_apps_cart_id_fkey'), 'user', type_='foreignkey')
    op.drop_column('user', 'apps_cart_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('apps_cart_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('user_apps_cart_id_fkey'), 'user', 'cart', ['apps_cart_id'], ['id'])
    # ### end Alembic commands ###
