"""empty message

Revision ID: 6e0c1a6215f2
Revises: 6b47735111db
Create Date: 2026-08-17 16:49:35.390634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e0c1a6215f2'
down_revision: Union[str, Sequence[str], None] = '6b47735111db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_covers', 'position')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_covers', sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
