"""Add user review app tables

Revision ID: 6e49a378e5bd
Revises: 
Create Date: 2026-06-22 15:03:04.761625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e49a378e5bd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('roles', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('registration_date', sa.Date(), nullable=False),
    sa.Column('balance', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    op.create_table('app',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=400), nullable=True),
    sa.Column('category', sa.Enum('APPLICATION', 'GAME', name='appcategory'), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('public', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('genre', sa.Enum('ADVENTURE', 'PUZZLE', 'RACING', 'SANDBOX', name='gamegenre'), nullable=True),
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.Column('keywords', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('publisher_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['publisher_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review',
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(length=400), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('creation_date', sa.Date(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('app_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['app.id'], ),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    op.drop_table('app')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
