"""add created_at columns on several tables

Revision ID: 7c5899b86529
Revises: a03610bee1dd
Create Date: 2026-07-24 19:20:06.915316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c5899b86529'
down_revision: Union[str, Sequence[str], None] = 'a03610bee1dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_archives', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('app_covers', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('carts', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_constraint(op.f('transfers_user_id_fkey'), 'transfers', type_='foreignkey')
    op.create_foreign_key(None, 'transfers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('user_profile_pictures', sa.Column('created_at', sa.DateTime(), nullable=False))

    op.alter_column('users', 'registered_at',
               existing_type=sa.dialects.postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    
    op.alter_column('apps', 'published_at',
               existing_type=sa.dialects.postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    
    op.alter_column('discussions', 'created_at',
               existing_type=sa.dialects.postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    
    op.alter_column('messages', 'created_at',
               existing_type=sa.dialects.postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    
    op.alter_column('reviews', 'created_at',
               existing_type=sa.dialects.postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)

    op.alter_column('app_covers', 'created_at',
               existing_type=sa.dialects.postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)

    op.alter_column('app_archives', 'created_at',
               existing_type=sa.dialects.postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)

    op.alter_column('transfers', 'made_at',
               existing_type=sa.dialects.postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    
    op.alter_column('purchases', 'purchased_at',
               existing_type=sa.dialects.postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)

    op.alter_column('cart_items', 'added_at',
               existing_type=sa.dialects.postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)

    op.alter_column('carts', 'created_at',
               existing_type=sa.dialects.postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    
def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile_pictures', 'created_at')
    op.drop_constraint(None, 'transfers', type_='foreignkey')
    op.create_foreign_key(op.f('transfers_user_id_fkey'), 'transfers', 'users', ['user_id'], ['id'])
    op.drop_column('carts', 'created_at')
    op.drop_column('app_covers', 'created_at')
    op.drop_column('app_archives', 'created_at')
    # ### end Alembic commands ###
