"""Add birth date to users table and app thumbnails table

Revision ID: 815c9125ba97
Revises: 7c5899b86529
Create Date: 2026-07-31 15:41:22.944583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '815c9125ba97'
down_revision: Union[str, Sequence[str], None] = '7c5899b86529'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_thumbnails',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('extension', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('app_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('apps', 'title',
               existing_type=sa.VARCHAR(length=40),
               type_=sqlmodel.sql.sqltypes.AutoString(length=64),
               existing_nullable=False)
    op.alter_column('user_profile_pictures', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.add_column('users', sa.Column('birth_date', sa.DATE(), nullable=True))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=30),
               type_=sqlmodel.sql.sqltypes.AutoString(length=64),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=64),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.drop_column('users', 'birth_date')
    op.alter_column('user_profile_pictures', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('apps', 'title',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=64),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False)
    op.drop_table('app_thumbnails')
    # ### end Alembic commands ###
