"""add extension

Revision ID: 8da9c533a100
Revises: 35b5cb142eeb
Create Date: 2026-07-19 17:34:35.011101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8da9c533a100'
down_revision: Union[str, Sequence[str], None] = '35b5cb142eeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_covers', sa.Column('extension', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('user_profile_pictures', sa.Column('extension', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile_pictures', 'extension')
    op.drop_column('app_covers', 'extension')
    # ### end Alembic commands ###
