"""Add purchase, cart, cart item tables

Revision ID: a85cf81c92e3
Revises: 027ff7435294
Create Date: 2026-06-25 13:54:28.595324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a85cf81c92e3'
down_revision: Union[str, Sequence[str], None] = '027ff7435294'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('cartitem',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('cart_id', sa.Uuid(), nullable=False),
    sa.Column('app_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['app.id'], ),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('purchased_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('app_id', sa.Uuid(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['app.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    #sa.PrimaryKeyConstraint('user_id'),
    #sa.PrimaryKeyConstraint('app_id'),
    )
    op.drop_table('apppurchase')
    op.drop_table('cartapp')
    op.add_column('user', sa.Column('apps_cart_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'user', 'cart', ['apps_cart_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'apps_cart_id')
    op.create_table('cartapp',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('added_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('app_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['app.id'], name=op.f('cartapp_app_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('cartapp_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('cartapp_pkey'))
    )
    op.create_table('apppurchase',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('purchased_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('app_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['app.id'], name=op.f('apppurchase_app_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('apppurchase_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('apppurchase_pkey'))
    )
    op.drop_table('purchase')
    op.drop_table('cartitem')
    op.drop_table('cart')
    # ### end Alembic commands ###
