"""Edit index

Revision ID: ae1897626871
Revises: 6e0c1a6215f2
Create Date: 2026-09-06 10:58:55.772818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae1897626871'
down_revision: Union[str, Sequence[str], None] = '6e0c1a6215f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('app_covers_app_id_fkey'), 'app_covers', type_='foreignkey')
    op.create_foreign_key(None, 'app_covers', 'apps', ['app_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_apps_keywords_gin'), table_name='apps', postgresql_using='gin', postgresql_where='public')
    op.create_index('ix_apps_keywords_gin_public', 'apps', ['keywords'], unique=False, postgresql_using='gin', postgresql_where='public = true')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_apps_keywords_gin_public', table_name='apps', postgresql_using='gin', postgresql_where='public = true')
    op.create_index(op.f('ix_apps_keywords_gin'), 'apps', ['keywords'], unique=False, postgresql_using='gin', postgresql_where='public')
    op.drop_constraint(None, 'app_covers', type_='foreignkey')
    op.create_foreign_key(op.f('app_covers_app_id_fkey'), 'app_covers', 'apps', ['app_id'], ['id'])
    # ### end Alembic commands ###
