"""Fix create_at datetimes and primary keys of tables

Revision ID: b5a16dbf7c76
Revises: 6e49a378e5bd
Create Date: 2026-06-23 17:24:25.500336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b5a16dbf7c76'
down_revision: Union[str, Sequence[str], None] = '6e49a378e5bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app', sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('app', sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('review', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('review', 'creation_date')
    op.add_column('user', sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_unique_constraint(None, 'user', ['email'])
    op.drop_column('user', 'registration_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('registration_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    op.drop_column('user', 'registered_at')
    op.add_column('review', sa.Column('creation_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('review', 'created_at')
    op.drop_column('app', 'category')
    op.drop_column('app', 'genre')
    op.drop_column('app', 'published_at')
    op.drop_column('app', 'version')
    # ### end Alembic commands ###
