"""add operation type column

Revision ID: d67fc8f6867a
Revises: f77d13b62008
Create Date: 2026-07-15 15:45:18.848586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd67fc8f6867a'
down_revision: Union[str, Sequence[str], None] = 'f77d13b62008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('BALANCE_TOP_UP', 'WITHDRAWAL_TO_CARD', name='operationtype').create(op.get_bind())
    op.add_column('transfers', sa.Column('operation_type', postgresql.ENUM('BALANCE_TOP_UP', 'WITHDRAWAL_TO_CARD', name='operationtype', create_type=False), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transfers', 'operation_type')
    sa.Enum('BALANCE_TOP_UP', 'WITHDRAWAL_TO_CARD', name='operationtype').drop(op.get_bind())
    # ### end Alembic commands ###
