"""empty message

Revision ID: e388e1f4105a
Revises: fe0b621cc949
Create Date: 2026-08-06 13:32:16.652117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e388e1f4105a'
down_revision: Union[str, Sequence[str], None] = 'fe0b621cc949'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profile_pictures')
    op.drop_table('app_archives')
    op.drop_table('app_thumbnails')
    op.add_column('app_covers', sa.Column('object_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('app_covers', sa.Column('position', sa.Integer(), nullable=False))
    op.alter_column('app_covers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_index(op.f('ix_app_covers_app_id'), 'app_covers', ['app_id'], unique=False)
    op.drop_column('app_covers', 'extension')
    op.add_column('apps', sa.Column('pending_icon_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('apps', sa.Column('icon_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('apps', 'pending_cover_key')
    op.drop_column('apps', 'cover_keys')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apps', sa.Column('cover_keys', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('apps', sa.Column('pending_cover_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('apps', 'icon_key')
    op.drop_column('apps', 'pending_icon_key')
    op.add_column('app_covers', sa.Column('extension', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_app_covers_app_id'), table_name='app_covers')
    op.alter_column('app_covers', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_column('app_covers', 'position')
    op.drop_column('app_covers', 'object_key')
    op.create_table('app_thumbnails',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('extension', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('app_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], name=op.f('app_thumbnails_app_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('app_thumbnails_pkey'))
    )
    op.create_table('app_archives',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('app_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], name=op.f('app_archives_app_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('app_archives_pkey'))
    )
    op.create_table('user_profile_pictures',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('extension', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_profile_pictures_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_profile_pictures_pkey'))
    )
    # ### end Alembic commands ###
