"""Add times_purchased column to apps table

Revision ID: f77d13b62008
Revises: 4535f94e6a1a
Create Date: 2026-07-14 14:36:02.540182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f77d13b62008'
down_revision: Union[str, Sequence[str], None] = '4535f94e6a1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apps', sa.Column('times_purchased', sa.Integer(), nullable=False))
    op.drop_column('apps', 'file_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apps', sa.Column('file_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_column('apps', 'times_purchased')
    # ### end Alembic commands ###
