"""Add pending and actual keys for MinIO S3 for app and user

Revision ID: fe0b621cc949
Revises: 815c9125ba97
Create Date: 2026-08-05 19:11:22.075721

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fe0b621cc949'
down_revision: Union[str, Sequence[str], None] = '815c9125ba97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apps', sa.Column('pending_archive_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('apps', sa.Column('archive_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('apps', sa.Column('pending_cover_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('apps', sa.Column('cover_keys', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('users', sa.Column('pending_avatar_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('avatar_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_key')
    op.drop_column('users', 'pending_avatar_key')
    op.drop_column('apps', 'cover_keys')
    op.drop_column('apps', 'pending_cover_key')
    op.drop_column('apps', 'archive_key')
    op.drop_column('apps', 'pending_archive_key')
    # ### end Alembic commands ###
